using System.Text.Json;
using MarpToPptx.Core;
using MarpToPptx.Core.Authoring;
using MarpToPptx.Core.Models;
using MarpToPptx.Pptx.Rendering;
using ModelContextProtocol.Server;

namespace MarpToPptx.Cli.Mcp;

[McpServerToolType]
public sealed class MarpToPptxTools
{
    private static readonly JsonSerializerOptions IndentedJson = new() { WriteIndented = true };

    /// <summary>
    /// Compile Marp-flavored Markdown into an editable PowerPoint (.pptx) file.
    /// This is the primary conversion tool. Provide the markdown content or a path to a .md file.
    /// Returns the absolute path to the generated .pptx file on success.
    /// </summary>
    /// <param name="inputMarkdownPath">Absolute path to the input Marp Markdown file.</param>
    /// <param name="outputPptxPath">Optional output path for the .pptx file. Defaults to the input file name with a .pptx extension.</param>
    /// <param name="themeCssPath">Optional absolute path to a CSS file with Marp-style theme values.</param>
    /// <param name="templatePath">Optional absolute path to an existing .pptx template to copy masters/themes from.</param>
    /// <param name="allowRemoteAssets">When true, enables HTTP/HTTPS image downloads during rendering. Defaults to false.</param>
    /// <param name="writeSlideIds">When true, writes missing slideId directives into the markdown file before rendering. Enables stable identity for future marp_update_deck calls.</param>
    [McpServerTool(Title = "Render Markdown to PPTX")]
    public Task<string> marp_render(
        string inputMarkdownPath,
        string? outputPptxPath = null,
        string? themeCssPath = null,
        string? templatePath = null,
        bool allowRemoteAssets = false,
        bool writeSlideIds = false)
    {
        try
        {
            inputMarkdownPath = ValidateFileExists(inputMarkdownPath, "Input Markdown");
            if (!string.IsNullOrWhiteSpace(themeCssPath))
                themeCssPath = ValidateFileExists(themeCssPath, "Theme CSS");
            if (!string.IsNullOrWhiteSpace(templatePath))
                templatePath = ValidateFileExists(templatePath, "Template PPTX");

            outputPptxPath ??= Path.ChangeExtension(inputMarkdownPath, ".pptx");
            outputPptxPath = Path.GetFullPath(outputPptxPath);

            var markdown = File.ReadAllText(inputMarkdownPath);
            var themeCss = string.IsNullOrWhiteSpace(themeCssPath) ? null : File.ReadAllText(themeCssPath);

            var compiler = new MarpCompiler();
            var deck = compiler.Compile(markdown, inputMarkdownPath, themeCss);

            var slideIdsAdded = 0;
            if (writeSlideIds)
            {
                var rewriteResult = SlideIdDirectiveWriter.WriteMissingSlideIds(markdown, deck);
                if (rewriteResult.AddedCount > 0)
                {
                    File.WriteAllText(inputMarkdownPath, rewriteResult.UpdatedMarkdown);
                    markdown = rewriteResult.UpdatedMarkdown;
                    deck = compiler.Compile(markdown, inputMarkdownPath, themeCss);
                    slideIdsAdded = rewriteResult.AddedCount;
                }
            }

            var renderer = new OpenXmlPptxRenderer();
            renderer.Render(deck, outputPptxPath, new PptxRenderOptions
            {
                TemplatePath = templatePath,
                SourceDirectory = Path.GetDirectoryName(inputMarkdownPath),
                AllowRemoteAssets = allowRemoteAssets,
            });

            var message = $"Generated '{outputPptxPath}' with {deck.Slides.Count} slide(s).";
            if (slideIdsAdded > 0)
                message += $" Added {slideIdsAdded} slideId directive(s) to '{inputMarkdownPath}'.";
            return Task.FromResult(message);
        }
        catch (Exception ex)
        {
            return Task.FromResult($"Error: {ex.Message}");
        }
    }

    /// <summary>
    /// Update a previously exported MarpToPptx deck by reconciling new Marp Markdown
    /// content against an existing .pptx file. Slides generated by MarpToPptx are updated
    /// in place while unmanaged slides (added manually in PowerPoint) are preserved.
    /// Use --write-slide-ids first to ensure slides have stable identity directives.
    /// </summary>
    /// <param name="inputMarkdownPath">Absolute path to the input Marp Markdown file.</param>
    /// <param name="existingDeckPath">Absolute path to the existing .pptx deck to update.</param>
    /// <param name="outputPptxPath">Optional output path. Defaults to the existing deck path (in-place update).</param>
    /// <param name="themeCssPath">Optional absolute path to a CSS file with Marp-style theme values.</param>
    /// <param name="allowRemoteAssets">When true, enables HTTP/HTTPS image downloads. Defaults to false.</param>
    [McpServerTool(Title = "Update Existing Deck")]
    public Task<string> marp_update_deck(
        string inputMarkdownPath,
        string existingDeckPath,
        string? outputPptxPath = null,
        string? themeCssPath = null,
        bool allowRemoteAssets = false)
    {
        try
        {
            inputMarkdownPath = ValidateFileExists(inputMarkdownPath, "Input Markdown");
            existingDeckPath = ValidateFileExists(existingDeckPath, "Existing deck");
            if (!string.IsNullOrWhiteSpace(themeCssPath))
                themeCssPath = ValidateFileExists(themeCssPath, "Theme CSS");

            outputPptxPath ??= existingDeckPath;
            outputPptxPath = Path.GetFullPath(outputPptxPath);

            var markdown = File.ReadAllText(inputMarkdownPath);
            var themeCss = string.IsNullOrWhiteSpace(themeCssPath) ? null : File.ReadAllText(themeCssPath);

            var compiler = new MarpCompiler();
            var deck = compiler.Compile(markdown, inputMarkdownPath, themeCss);

            var renderer = new OpenXmlPptxRenderer();
            renderer.Render(deck, outputPptxPath, new PptxRenderOptions
            {
                SourceDirectory = Path.GetDirectoryName(inputMarkdownPath),
                AllowRemoteAssets = allowRemoteAssets,
                ExistingDeckPath = existingDeckPath,
            });

            return Task.FromResult($"Updated '{outputPptxPath}' with {deck.Slides.Count} slide(s).");
        }
        catch (Exception ex)
        {
            return Task.FromResult($"Error: {ex.Message}");
        }
    }

    /// <summary>
    /// Inspect a Marp Markdown file and return structured metadata about the deck
    /// without generating a .pptx file. Returns slide count, per-slide titles,
    /// front-matter directives, theme information, and presenter notes.
    /// Use this to understand or validate a deck before rendering.
    /// </summary>
    /// <param name="inputMarkdownPath">Absolute path to the Marp Markdown file.</param>
    /// <param name="themeCssPath">Optional absolute path to a CSS theme file.</param>
    [McpServerTool(Title = "Inspect Deck", ReadOnly = true, Idempotent = true)]
    public Task<string> marp_inspect(
        string inputMarkdownPath,
        string? themeCssPath = null)
    {
        try
        {
            inputMarkdownPath = ValidateFileExists(inputMarkdownPath, "Input Markdown");
            if (!string.IsNullOrWhiteSpace(themeCssPath))
                themeCssPath = ValidateFileExists(themeCssPath, "Theme CSS");

            var markdown = File.ReadAllText(inputMarkdownPath);
            var themeCss = string.IsNullOrWhiteSpace(themeCssPath) ? null : File.ReadAllText(themeCssPath);

            var compiler = new MarpCompiler();
            var deck = compiler.Compile(markdown, inputMarkdownPath, themeCss);
            var identities = SlideIdentityGenerator.BuildSlideIdentities(deck);

            var result = new
            {
                deckId = SlideIdentityGenerator.ComputeDeckId(deck),
                title = SlideIdentityGenerator.GetPresentationTitle(deck),
                theme = deck.Theme,
                slideCount = deck.Slides.Count,
                slides = deck.Slides.Select((slide, index) => new
                {
                    index,
                    title = SlideIdentityGenerator.GetSlideTitle(slide),
                    slideId = index < identities.Count ? identities[index].SlideId : null,
                    hasNotes = !string.IsNullOrWhiteSpace(slide.Notes),
                    elementCount = slide.Elements.Count,
                    backgroundImage = slide.Style.BackgroundImage,
                    backgroundColor = slide.Style.BackgroundColor,
                    className = slide.Style.ClassName,
                }).ToArray(),
            };

            return Task.FromResult(JsonSerializer.Serialize(result, IndentedJson));
        }
        catch (Exception ex)
        {
            return Task.FromResult($"Error: {ex.Message}");
        }
    }

    /// <summary>
    /// Write stable slideId directives into a Marp Markdown file for slides that
    /// do not already have them. This enables the re-entrant update workflow where
    /// marp_update_deck can reconcile slide changes by identity.
    /// Returns the number of slideId directives added.
    /// </summary>
    /// <param name="inputMarkdownPath">Absolute path to the Marp Markdown file to update in place.</param>
    /// <param name="themeCssPath">Optional absolute path to a CSS theme file.</param>
    [McpServerTool(Title = "Write Slide IDs")]
    public Task<string> marp_write_slide_ids(
        string inputMarkdownPath,
        string? themeCssPath = null)
    {
        try
        {
            inputMarkdownPath = ValidateFileExists(inputMarkdownPath, "Input Markdown");
            if (!string.IsNullOrWhiteSpace(themeCssPath))
                themeCssPath = ValidateFileExists(themeCssPath, "Theme CSS");

            var markdown = File.ReadAllText(inputMarkdownPath);
            var themeCss = string.IsNullOrWhiteSpace(themeCssPath) ? null : File.ReadAllText(themeCssPath);

            var compiler = new MarpCompiler();
            var deck = compiler.Compile(markdown, inputMarkdownPath, themeCss);

            var rewriteResult = SlideIdDirectiveWriter.WriteMissingSlideIds(markdown, deck);
            if (rewriteResult.AddedCount > 0)
            {
                File.WriteAllText(inputMarkdownPath, rewriteResult.UpdatedMarkdown);
                return Task.FromResult($"Added {rewriteResult.AddedCount} slideId directive(s) to '{inputMarkdownPath}'.");
            }

            return Task.FromResult("All slides already have slideId directives. No changes made.");
        }
        catch (Exception ex)
        {
            return Task.FromResult($"Error: {ex.Message}");
        }
    }

    /// <summary>
    /// Compile Marp Markdown provided as a string (rather than a file) into a .pptx file.
    /// Useful when the markdown content is generated or composed programmatically by the LLM.
    /// Returns the absolute path to the generated .pptx file on success.
    /// </summary>
    /// <param name="markdown">The Marp-flavored Markdown content to compile.</param>
    /// <param name="outputPptxPath">Absolute path for the output .pptx file.</param>
    /// <param name="themeCss">Optional CSS theme content (not a file path).</param>
    /// <param name="templatePath">Optional absolute path to an existing .pptx template.</param>
    [McpServerTool(Title = "Render Markdown String to PPTX")]
    public Task<string> marp_render_string(
        string markdown,
        string outputPptxPath,
        string? themeCss = null,
        string? templatePath = null)
    {
        try
        {
            if (string.IsNullOrWhiteSpace(markdown))
                return Task.FromResult("Error: Markdown content is required.");
            if (string.IsNullOrWhiteSpace(outputPptxPath))
                return Task.FromResult("Error: Output path is required.");

            outputPptxPath = Path.GetFullPath(outputPptxPath);
            if (!string.IsNullOrWhiteSpace(templatePath))
                templatePath = ValidateFileExists(templatePath, "Template PPTX");

            var compiler = new MarpCompiler();
            var deck = compiler.Compile(markdown, sourcePath: null, themeCss);

            var renderer = new OpenXmlPptxRenderer();
            renderer.Render(deck, outputPptxPath, new PptxRenderOptions
            {
                TemplatePath = templatePath,
            });

            return Task.FromResult($"Generated '{outputPptxPath}' with {deck.Slides.Count} slide(s).");
        }
        catch (Exception ex)
        {
            return Task.FromResult($"Error: {ex.Message}");
        }
    }

    private static string ValidateFileExists(string path, string description)
    {
        var fullPath = Path.GetFullPath(path);
        if (!File.Exists(fullPath))
            throw new FileNotFoundException($"{description} file was not found: {fullPath}", fullPath);
        return fullPath;
    }
}
