namespace MarpToPptx.Pptx.Rendering;

public sealed class PptxRenderOptions
{
    public string? TemplatePath { get; init; }

    public string? SourceDirectory { get; init; }

    /// <summary>
    /// When <c>true</c>, HTTP and HTTPS image URLs are fetched at render time.
    /// The default is <c>false</c>, which treats all remote references as missing assets
    /// and avoids outbound HTTP(S) requests unless explicitly enabled.
    /// </summary>
    public bool AllowRemoteAssets { get; init; } = false;

    /// <summary>
    /// Optional <see cref="HttpMessageHandler"/> used when fetching remote assets.
    /// Primarily intended for unit-testing; when <c>null</c> the renderer uses a
    /// shared <see cref="HttpClient"/> with a 30-second timeout.
    /// </summary>
    public HttpMessageHandler? RemoteAssetHandler { get; init; }

    /// <summary>
    /// When set and the file exists, the renderer operates in update mode: existing slides
    /// generated by MarpToPptx are reconciled against the new Marp content in place,
    /// while slides not generated by MarpToPptx (unmanaged slides) are preserved.
    /// <para>
    /// In most cases this is the same path as the output; the renderer copies the file
    /// to the output location when the two paths differ.
    /// </para>
    /// </summary>
    public string? ExistingDeckPath { get; init; }
}
